package constants

var (
	ErrGetTokenFail         = "获取token失败"
	OperateSuccess          = "操作成功"
	OperateFail             = "操作失败"
	GetSuccess              = "获取成功"
	GetFail                 = "获取失败"
	UploadSuccess           = "上传成功"
	UploadFail              = "上传失败"
	DeleteSuccess           = "删除成功"
	DeleteFail              = "删除失败"
	BatchDeleteSuccess      = "批量删除成功"
	BatchDeleteFail         = "批量删除失败"
	UsernameOrPasswordError = "用户名不存在或者密码错误"
	UserBanLogin            = "用户被禁止登录"
	PhoneAndEmailEmpty      = "手机号和邮件为空"
	PasswordEmpty           = "密码为空!"
	InviteCodeEmpty         = "邀请码必填!"
	CaptchaError            = "验证码错误"
	RegisterFail            = "注册失败!"
	NewPasswordSameAsOld    = "新密码不能与原密码相同"
	BindSuccess             = "绑定成功"
	BindFail                = "绑定失败"
	StatusCodeError         = "状态码错误！"
	AuditSuccess            = "审核成功"
	AuditFail               = "审核失败"
	Auditing                = "审核中"
	SetLoginStatusFail      = "设置登录状态失败"
	LoginSuccess            = "登录成功"
	AuthenticationSuccess   = "认证成功"
	AuthenticationFail      = "认证失败"
	ParamError              = "参数错误"
	GetCountryInfoFail      = "获取国家信息失败"
	GetCaptchaSuccess       = "验证码获取成功"
	GetCaptchaFail          = "验证码获取失败"
	ParentUserNotExist      = "上级用户不存在"
	CreateFundAccountFail   = "资金账户创建失败!"
)
